version: '3.7'
services:

#  fixa-api:
#    image: goreit/fixa-api
#    volumes:
#       - goreit-main-api-data:/root
#    ports:
#       - 8081:8081
#       - 5000:5000
#    depends_on:
#       - 'mongodb'
#       - 'postgres'
#    environment:
#      SPRING_PROFILES_ACTIVE: "dev"
#    networks:
#      - goreit

  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - keycloak-data:/var/lib/keycloak/data
    networks:
      - goreit
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000M
    environment:
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
    volumes:
      - rabbitmq-data:/data/mq
    networks:
      - goreit


  mongodb:
    image: mongo:4.0.0
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
    command: mongod
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000M
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - goreit


  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
      PGDATA: var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - goreit

networks:
  goreit:

volumes:
  main-api-data:
  rabbitmq-data:
  mongodb-data:
  solr-data:
  postgres-data:
  keycloak-data:


