---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 27017
      nodePort: 30081
  selector:
    app: mongo